Repository vagator/test-prow, pull requests merged in 2021-12, with the labels that each got.

#4 Update README.md
  README.md
Labels: size/XS

#6 Update README.md
  README.md
Labels: lgtm, size/XS, approved

#7 Test PR merging: Update README
  README.md
Labels: lgtm, size/XS, approved

#8 Update README.md for testing Purpose
  README.md
Labels: lgtm, size/XS, approved, ok-to-test
